{
  lib,
  stdenv,
  bash,
  bun,
  bun2nix,
  electron_44,
  git,
  gnumake,
  makeWrapper,
  nodejs,
  src,
  version,
  sourceDateEpoch,
}:
let
  # The overlay builds with the consumer's nixpkgs (any bun, any platform),
  # so nothing may hash `bun install` output. bun.lock is the only record
  # of our dependencies and already has a sha512 per package; Nix fetches
  # each one with it, and bun links node_modules offline in the build.
  # bun.lock is JSON with trailing commas: drop them and read it at eval time.
  # Each package is [ "name@version" registry meta "sha512-..." ].
  bunLock = builtins.fromJSON (
    lib.concatMapStrings (p: if builtins.isList p then builtins.head p else p) (
      builtins.split ",([[:space:]]*[]}])" (builtins.readFile (src + "/bun.lock"))
    )
  );
  host = stdenv.hostPlatform.node;
  # Fetch only what bun installs on this platform.
  keep =
    entry:
    let
      id = builtins.head entry;
      meta = builtins.elemAt entry 2;
      # bun writes os/cpu as the values a package allows or, when that
      # list would be longer, as "!value" for the ones it excludes.
      allows =
        field: value:
        let
          values = lib.toList (meta.${field} or [ ]);
        in
        !builtins.elem "!${value}" values
        && (builtins.all (lib.hasPrefix "!") values || builtins.elem value values);
    in
    assert lib.assertMsg (builtins.length entry == 4 && builtins.elemAt entry 1 == "")
      "bun.lock: ${id} is not a default-registry npm package; generate a bun.nix with the bun2nix CLI instead of reading bun.lock";
    allows "os" host.platform && allows "cpu" host.arch;
  # Same shape as a bun.nix generated by the bun2nix CLI.
  bunNix =
    { fetchurl, ... }:
    lib.listToAttrs (
      map (
        entry:
        let
          id = builtins.elemAt entry 0;
          nameVersion = builtins.match "(@?[^@]+)@(.+)" id;
          name = builtins.elemAt nameVersion 0;
        in
        lib.nameValuePair id (fetchurl {
          url = "https://registry.npmjs.org/${name}/-/${baseNameOf name}-${builtins.elemAt nameVersion 1}.tgz";
          hash = builtins.elemAt entry 3;
        })
      ) (builtins.filter keep (builtins.attrValues bunLock.packages))
    );
  bunDeps = bun2nix.fetchBunDeps {
    inherit bunNix;
    overrides = bun2nix.patchedDependenciesToOverrides {
      patchedDependencies = lib.mapAttrs (_: p: src + "/${p}") bunLock.patchedDependencies;
    };
    # Shebangs are patched after the install, so they point at nodejs, not bun.
    patchShebangs = false;
  };
in
stdenv.mkDerivation rec {
  pname = "xum";
  inherit version src;

  SOURCE_DATE_EPOCH = toString sourceDateEpoch;

  nativeBuildInputs = [
    bun2nix.hook
    nodejs
    makeWrapper
    gnumake
    git # Needed by scripts/generate-version.sh
  ];

  inherit bunDeps;
  # Hoisted gives the same tree as a dev `bun install`. The cache is
  # read-only store paths, so copy files. Fail if bun.lock is stale.
  bunInstallFlags = [
    "--linker=hoisted"
    "--backend=copyfile"
    "--frozen-lockfile"
  ];
  # Some install scripts download binaries (e.g. geckodriver), and the sandbox has no network.
  dontRunLifecycleScripts = true;

  buildInputs = [
    # Pin the major Electron version explicitly so `pkgs.electron`
    # floating to a new major doesn't silently ship the wrong
    # Node.js ABI for our prebuilt native modules.
    electron_44
    stdenv.cc.cc.lib # Provides libstdc++ for native modules like sharp
  ];

  # bun2nix.hook sets HOME, patches source shebangs and runs `bun install` before this.
  buildPhase = ''
    chmod -R u+w node_modules
    patchShebangs node_modules
    # Keep make from running its own bun install.
    touch node_modules/.installed

    echo "Building xum with make..."
    export LD_LIBRARY_PATH="${stdenv.cc.cc.lib}/lib:$LD_LIBRARY_PATH"
    # Nix strips .git from the build sandbox, so generate-version.sh's
    # git describe/rev-parse fall back to "unknown". Feed the revision
    # the flake already resolved so the version stamp is accurate.
    export RELEASE_TAG="${version}"
    export XUM_GIT_COMMIT="${builtins.substring 0 12 version}"
    make SHELL=${bash}/bin/bash build
  '';

  installPhase = ''
    mkdir -p $out/lib/xum
    mkdir -p $out/bin

    # Copy built files and runtime dependencies
    cp -r dist $out/lib/xum/
    cp -r node_modules $out/lib/xum/
    cp package.json $out/lib/xum/

    # Keep one canonical wrapper and make the old command a symlink so
    # nix profile upgrades/downgrades never fork the implementation.
    makeWrapper ${electron_44}/bin/electron $out/bin/xum \
      --add-flags "$out/lib/xum/dist/cli/index.js" \
      --set XUM_E2E_LOAD_DIST "1" \
      --prefix LD_LIBRARY_PATH : "${stdenv.cc.cc.lib}/lib" \
      --prefix PATH : ${
        lib.makeBinPath [
          git
          bash
        ]
      }
    ln -s xum $out/bin/mux

    # Install canonical launcher assets and leave old filenames pointing forward.
    install -Dm644 public/icon.png $out/share/icons/hicolor/512x512/apps/xum.png
    ln -s xum.png $out/share/icons/hicolor/512x512/apps/mux.png
    mkdir -p $out/share/applications
    cat > $out/share/applications/xum.desktop << EOF
    [Desktop Entry]
    Name=Xum
    GenericName=Coding Agent Multiplexer
    Comment=Coding Agent Multiplexer
    Exec=$out/bin/xum %U
    Icon=xum
    Terminal=false
    Type=Application
    Categories=Development;
    StartupWMClass=xum
    EOF
    ln -s xum.desktop $out/share/applications/mux.desktop
  '';

  meta = with lib; {
    description = "xum - coding agent multiplexer";
    homepage = "https://github.com/coder/mux";
    license = licenses.agpl3Only;
    # nixpkgs builds bun only for some platforms (no x86_64-darwin).
    platforms = bun.meta.platforms;
    mainProgram = "xum";
  };
}
