{
  description = "xum - coding agent multiplexer";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    # Pinned to a tag: bunNix below relies on how fetchBunDeps calls it.
    bun2nix = {
      url = "github:nix-community/bun2nix/2.1.2";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
      bun2nix,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ bun2nix.overlays.default ];
        };
        inherit (pkgs) lib;

        # Consumers often make nixpkgs follow their own (any bun, any platform),
        # so nothing may hash `bun install` output. bun.lock is the only record
        # of our dependencies and already has a sha512 per package; Nix fetches
        # each one with it, and bun links node_modules offline in the build.
        # bun.lock is JSON with trailing commas: drop them and read it at eval time.
        # Each package is [ "name@version" registry meta "sha512-..." ].
        bunLock = builtins.fromJSON (
          lib.concatMapStrings (p: if builtins.isList p then builtins.head p else p) (
            builtins.split ",([[:space:]]*[]}])" (builtins.readFile ./bun.lock)
          )
        );
        host = pkgs.stdenv.hostPlatform.node;
        # Fetch only what bun installs on this platform.
        keep =
          entry:
          let
            id = builtins.head entry;
            meta = builtins.elemAt entry 2;
            # bun writes os/cpu as the values a package allows or, when that
            # list would be longer, as "!value" for the ones it excludes.
            allows =
              field: value:
              let
                values = lib.toList (meta.${field} or [ ]);
              in
              !builtins.elem "!${value}" values
              && (builtins.all (lib.hasPrefix "!") values || builtins.elem value values);
          in
          assert lib.assertMsg (builtins.length entry == 4 && builtins.elemAt entry 1 == "")
            "bun.lock: ${id} is not a default-registry npm package; generate a bun.nix with the bun2nix CLI instead of reading bun.lock";
          allows "os" host.platform && allows "cpu" host.arch;
        # Same shape as a bun.nix generated by the bun2nix CLI.
        bunNix =
          { fetchurl, ... }:
          lib.listToAttrs (
            map (
              entry:
              let
                id = builtins.elemAt entry 0;
                nameVersion = builtins.match "(@?[^@]+)@(.+)" id;
                name = builtins.elemAt nameVersion 0;
              in
              lib.nameValuePair id (fetchurl {
                url = "https://registry.npmjs.org/${name}/-/${baseNameOf name}-${builtins.elemAt nameVersion 1}.tgz";
                hash = builtins.elemAt entry 3;
              })
            ) (builtins.filter keep (builtins.attrValues bunLock.packages))
          );
        bunDeps = pkgs.bun2nix.fetchBunDeps {
          inherit bunNix;
          overrides = pkgs.bun2nix.patchedDependenciesToOverrides {
            patchedDependencies = lib.mapAttrs (_: p: ./. + "/${p}") bunLock.patchedDependencies;
          };
          # Shebangs are patched after the install, so they point at nodejs, not bun.
          patchShebangs = false;
        };

        xum = pkgs.stdenv.mkDerivation rec {
          pname = "xum";
          version = self.rev or self.dirtyRev or "dev";

          src = ./.;

          # Stamp buildTime from the flake's source date so the output is reproducible.
          SOURCE_DATE_EPOCH = toString (self.lastModified or 315532800);

          nativeBuildInputs = with pkgs; [
            pkgs.bun2nix.hook # `with` does not shadow the bun2nix flake input
            nodejs
            makeWrapper
            gnumake
            git # Needed by scripts/generate-version.sh
          ];

          inherit bunDeps;
          # Hoisted gives the same tree as a dev `bun install`. The cache is
          # read-only store paths, so copy files. Fail if bun.lock is stale.
          bunInstallFlags = [
            "--linker=hoisted"
            "--backend=copyfile"
            "--frozen-lockfile"
          ];
          # Some install scripts download binaries (e.g. geckodriver), and the sandbox has no network.
          dontRunLifecycleScripts = true;

          buildInputs = with pkgs; [
            # Pin the major Electron version explicitly so `pkgs.electron`
            # floating to a new major doesn't silently ship the wrong
            # Node.js ABI for our prebuilt native modules.
            electron_44
            stdenv.cc.cc.lib # Provides libstdc++ for native modules like sharp
          ];

          # bun2nix.hook sets HOME, patches source shebangs and runs `bun install` before this.
          buildPhase = ''
            chmod -R u+w node_modules
            patchShebangs node_modules
            # Keep make from running its own bun install.
            touch node_modules/.installed

            echo "Building xum with make..."
            export LD_LIBRARY_PATH="${pkgs.stdenv.cc.cc.lib}/lib:$LD_LIBRARY_PATH"
            # Nix strips .git from the build sandbox, so generate-version.sh's
            # git describe/rev-parse fall back to "unknown". Feed the revision
            # the flake already resolved so the version stamp is accurate.
            export RELEASE_TAG="${version}"
            export XUM_GIT_COMMIT="${builtins.substring 0 12 version}"
            make SHELL=${pkgs.bash}/bin/bash build
          '';

          installPhase = ''
                        mkdir -p $out/lib/xum
                        mkdir -p $out/bin

                        # Copy built files and runtime dependencies
                        cp -r dist $out/lib/xum/
                        cp -r node_modules $out/lib/xum/
                        cp package.json $out/lib/xum/

                        # Keep one canonical wrapper and make the old command a symlink so
                        # nix profile upgrades/downgrades never fork the implementation.
                        makeWrapper ${pkgs.electron_44}/bin/electron $out/bin/xum \
                          --add-flags "$out/lib/xum/dist/cli/index.js" \
                          --set XUM_E2E_LOAD_DIST "1" \
                          --prefix LD_LIBRARY_PATH : "${pkgs.stdenv.cc.cc.lib}/lib" \
                          --prefix PATH : ${
                            pkgs.lib.makeBinPath [
                              pkgs.git
                              pkgs.bash
                            ]
                          }
                        ln -s xum $out/bin/mux

                        # Install canonical launcher assets and leave old filenames pointing forward.
                        install -Dm644 public/icon.png $out/share/icons/hicolor/512x512/apps/xum.png
                        ln -s xum.png $out/share/icons/hicolor/512x512/apps/mux.png
                        mkdir -p $out/share/applications
                        cat > $out/share/applications/xum.desktop << EOF
            [Desktop Entry]
            Name=Xum
            GenericName=Coding Agent Multiplexer
            Comment=Coding Agent Multiplexer
            Exec=$out/bin/xum %U
            Icon=xum
            Terminal=false
            Type=Application
            Categories=Development;
            StartupWMClass=xum
            EOF
                        ln -s xum.desktop $out/share/applications/mux.desktop
          '';

          meta = with pkgs.lib; {
            description = "xum - coding agent multiplexer";
            homepage = "https://github.com/coder/mux";
            license = licenses.agpl3Only;
            # nixpkgs builds bun only for some platforms (no x86_64-darwin).
            platforms = pkgs.bun.meta.platforms;
            mainProgram = "xum";
          };
        };
      in
      {
        packages.default = xum;
        packages.xum = xum;
        packages.mux = xum;

        formatter = pkgs.nixfmt;

        apps.default = {
          type = "app";
          program = "${xum}/bin/xum";
        };
        apps.xum = {
          type = "app";
          program = "${xum}/bin/xum";
        };
        apps.mux = {
          type = "app";
          program = "${xum}/bin/mux";
        };

        devShells.default = pkgs.mkShell {
          buildInputs =
            with pkgs;
            [
              bun

              # Node + build tooling
              nodejs
              gnumake
              stdenv.cc.cc.lib # Provides libstdc++.so.6 for DuckDB native bindings under Bun

              # Common CLIs
              git
              bash

              # Nix tooling
              nixfmt

              # Repo linting (make static-check)
              go
              hadolint
              shellcheck
              shfmt
              gh
              jq
              duckdb

              # Documentation
              mdbook
              mdbook-mermaid
              mdbook-linkcheck2
              mdbook-pagetoc

              # Browser automation
              agent-browser

              # Terminal bench + browser recording
              uv
              asciinema
              ffmpeg
            ]
            ++ lib.optionals stdenv.hostPlatform.isLinux [
              docker
              # The Electron binary shipped in node_modules/electron/dist
              # is dynamically linked against standard FHS paths
              # (libglib-2.0.so.0, libnss3.so, etc.) that don't exist on
              # NixOS, so `make start` / `make dev` fail with "error while
              # loading shared libraries". Expose Nix's autoPatchelf'd
              # Electron and redirect the npm wrapper to it via
              # ELECTRON_OVERRIDE_DIST_PATH below.
              electron_44
            ];

          # Bun does not carry libstdc++ on Linux, so native modules like @duckdb/node-bindings
          # fail to dlopen during tests unless we expose the GCC runtime in the shell.
          LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib ];

          # Point `node_modules/electron/cli.js` at the Nix-patched Electron
          # binary on Linux so `bunx electron` (used by `make start`/`make dev`)
          # finds its shared libraries on NixOS without needing an FHS wrapper.
          # Left unset on Darwin where the npm-shipped binary runs as-is.
          ELECTRON_OVERRIDE_DIST_PATH = pkgs.lib.optionalString pkgs.stdenv.hostPlatform.isLinux "${pkgs.electron_44}/libexec/electron";
        };
      }
    );
}
