export const SERVER_UPDATE_CHECK_TIMEOUT_MS = 30_000;
export const SERVER_UPDATE_INSTALL_TIMEOUT_MS = 5 * 60_000;
export const SERVER_UPDATE_SMOKE_TIMEOUT_MS = 30_000;
export const SERVER_UPDATE_STAGING_PREFIX = "xum-staging-";
export const SERVER_VERSION_CHECK_TIMEOUT_MS = 5_000;
