import type { ChatMuxMessage } from "@/common/orpc/types";
import type {
  BashMonitorWakeDisplayRecord,
  MuxMessageMetadata,
  MuxTextPart,
  MuxReasoningPart,
  MuxFilePart,
  MuxToolPart,
} from "@/common/types/message";
import { formatSubagentReportEnvelope } from "@/common/utils/subagentReportEnvelope";
import {
  type AgentMessageRelationship,
  formatAgentMessageEnvelope,
} from "@/common/utils/agentMessageEnvelope";
import type { ThinkingLevel } from "@/common/types/thinking";
import { DEFAULT_MODEL } from "@/common/constants/knownModels";
import {
  GOAL_BUDGET_LIMIT_KIND,
  GOAL_CONTINUATION_KIND,
  type GoalSyntheticMessageKind,
} from "@/constants/goals";
import { STABLE_TIMESTAMP } from "./workspaces";

/** Part type for message construction */
type MuxPart = MuxTextPart | MuxReasoningPart | MuxFilePart | MuxToolPart;

// ═══════════════════════════════════════════════════════════════════════════════
// MESSAGE FACTORY
// ═══════════════════════════════════════════════════════════════════════════════
export function createUserMessage(
  id: string,
  text: string,
  opts: {
    historySequence: number;
    timestamp?: number;
    images?: string[];
    muxMetadata?: MuxMessageMetadata;
    /** Mark as synthetic (auto-generated by system, not user-typed). Shows "AUTO" badge. */
    synthetic?: boolean;
  }
): ChatMuxMessage {
  const parts: MuxPart[] = [{ type: "text", text }];
  if (opts.images) {
    for (const url of opts.images) {
      parts.push({ type: "file", mediaType: "image/png", url });
    }
  }
  return {
    type: "message",
    id,
    role: "user",
    parts,
    metadata: {
      historySequence: opts.historySequence,
      timestamp: opts.timestamp ?? STABLE_TIMESTAMP,
      muxMetadata: opts.muxMetadata,
      ...(opts.synthetic && { synthetic: true, uiVisible: true }),
    },
  };
}

function createGoalSyntheticMessage(
  id: string,
  text: string,
  opts: { historySequence: number; timestamp?: number },
  kind: GoalSyntheticMessageKind
): ChatMuxMessage {
  return {
    type: "message",
    id,
    role: "user",
    parts: [{ type: "text", text }],
    metadata: {
      historySequence: opts.historySequence,
      timestamp: opts.timestamp ?? STABLE_TIMESTAMP,
      synthetic: true,
      uiVisible: true,
      kind,
    },
  };
}

export function createGoalBudgetLimitMessage(
  id: string,
  text: string,
  opts: { historySequence: number; timestamp?: number }
): ChatMuxMessage {
  return createGoalSyntheticMessage(id, text, opts, GOAL_BUDGET_LIMIT_KIND);
}

export function createGoalContinuationMessage(
  id: string,
  text: string,
  opts: { historySequence: number; timestamp?: number }
): ChatMuxMessage {
  return createGoalSyntheticMessage(id, text, opts, GOAL_CONTINUATION_KIND);
}

/**
 * Create a synthetic bash-monitor wake message. Renders as a compact card
 * (title + per-monitor summary) with the full prompt collapsed by default.
 */
export function createBashMonitorWakeMessage(
  id: string,
  opts: {
    historySequence: number;
    timestamp?: number;
    /** Full wake prompt (message text) revealed by the "Show details" toggle. */
    promptText: string;
    records: BashMonitorWakeDisplayRecord[];
  }
): ChatMuxMessage {
  return {
    type: "message",
    id,
    role: "user",
    parts: [{ type: "text", text: opts.promptText }],
    metadata: {
      historySequence: opts.historySequence,
      timestamp: opts.timestamp ?? STABLE_TIMESTAMP,
      synthetic: true,
      uiVisible: true,
      muxMetadata: {
        type: "bash-monitor-wake",
        records: opts.records,
      },
    },
  };
}

/** Create the synthetic envelope used for intra-tree agent peer messages. */
export function createAgentPeerMessage(
  id: string,
  opts: {
    historySequence: number;
    timestamp?: number;
    fromWorkspaceId: string;
    fromTitle?: string;
    relationship: AgentMessageRelationship;
    message: string;
  }
): ChatMuxMessage {
  return {
    type: "message",
    id,
    // SECURITY parity with sendAgentPeerMessage: payloads are assistant-role synthetic pre-turn
    // rows so peer bytes never gain user-role authority; the turn is triggered separately by a
    // fixed-content user message.
    role: "assistant",
    parts: [
      {
        type: "text",
        text: formatAgentMessageEnvelope({
          from: opts.fromWorkspaceId,
          ...(opts.fromTitle != null ? { fromTitle: opts.fromTitle } : {}),
          relationship: opts.relationship,
          message: opts.message,
        }),
      },
    ],
    metadata: {
      historySequence: opts.historySequence,
      timestamp: opts.timestamp ?? STABLE_TIMESTAMP,
      // Match the backend send path: synthetic sends are marked uiVisible so the
      // aggregator does not hide them from the transcript (agentSession internal sends).
      synthetic: true,
      uiVisible: true,
      muxMetadata: {
        type: "agent-peer-message",
        fromWorkspaceId: opts.fromWorkspaceId,
        ...(opts.fromTitle != null ? { fromTitle: opts.fromTitle } : {}),
        relationship: opts.relationship,
      },
    },
  };
}

/** Create the synthetic protocol envelope used to wake a parent with sub-agent findings. */
export function createSubagentReportMessage(
  id: string,
  opts: {
    historySequence: number;
    timestamp?: number;
    taskId: string;
    agentType: string;
    title: string;
    reportMarkdown: string;
    status?: "in_progress" | "completed";
    model?: string;
    thinkingLevel?: ThinkingLevel;
    structuredOutput?: unknown;
  }
): ChatMuxMessage {
  return createUserMessage(
    id,
    formatSubagentReportEnvelope({
      taskId: opts.taskId,
      agentType: opts.agentType,
      status: opts.status ?? "completed",
      title: opts.title,
      reportMarkdown: opts.reportMarkdown,
      ...(opts.model !== undefined ? { model: opts.model } : {}),
      ...(opts.thinkingLevel !== undefined ? { thinkingLevel: opts.thinkingLevel } : {}),
      ...(opts.structuredOutput !== undefined ? { structuredOutput: opts.structuredOutput } : {}),
    }),
    {
      historySequence: opts.historySequence,
      timestamp: opts.timestamp,
      synthetic: true,
    }
  );
}

/** Create a compaction request user message (triggers shimmer effect on streaming response) */
export function createCompactionRequestMessage(
  id: string,
  opts: { historySequence: number; timestamp?: number; rawCommand?: string }
): ChatMuxMessage {
  const rawCommand = opts.rawCommand ?? "/compact";
  return {
    type: "message",
    id,
    role: "user",
    parts: [{ type: "text", text: rawCommand }],
    metadata: {
      historySequence: opts.historySequence,
      timestamp: opts.timestamp ?? STABLE_TIMESTAMP,
      muxMetadata: {
        type: "compaction-request",
        rawCommand,
        parsed: {},
      },
    },
  };
}

export function createAssistantMessage(
  id: string,
  text: string,
  opts: {
    historySequence: number;
    timestamp?: number;
    model?: string;
    reasoning?: string;
    toolCalls?: MuxPart[];
    /** Mark as partial/interrupted message (unfinished stream) */
    partial?: boolean;
    /** Custom context usage for testing context meter display */
    contextUsage?: { inputTokens: number; outputTokens: number; totalTokens?: number };
  }
): ChatMuxMessage {
  const parts: MuxPart[] = [];
  if (opts.reasoning) {
    parts.push({ type: "reasoning", text: opts.reasoning });
  }
  parts.push({ type: "text", text });
  if (opts.toolCalls) {
    parts.push(...opts.toolCalls);
  }
  const contextUsage = opts.contextUsage ?? {
    inputTokens: 100,
    outputTokens: 50,
    totalTokens: 150,
  };
  contextUsage.totalTokens ??= contextUsage.inputTokens + contextUsage.outputTokens;
  return {
    type: "message",
    id,
    role: "assistant",
    parts,
    metadata: {
      historySequence: opts.historySequence,
      timestamp: opts.timestamp ?? STABLE_TIMESTAMP,
      model: opts.model ?? DEFAULT_MODEL,
      usage: contextUsage,
      contextUsage,
      duration: 1000,
      partial: opts.partial,
    },
  };
}
