// noVNC sets its viewOnly guard before ungrabbing the keyboard, discarding the key-ups
// generated by ungrab(). Release held inputs on the canvas first, while noVNC can still
// translate them. Keep this adapter local to the viewer; never synthesize a window blur.
export function trackDesktopInput(canvas: HTMLCanvasElement, isControlling: () => boolean) {
  const keys = new Map<string, KeyboardEvent>();
  const buttons = new Set<number>();
  let position = { clientX: 0, clientY: 0 };

  const keyDown = (event: KeyboardEvent) => {
    if (isControlling()) keys.set(event.code, event);
  };
  const keyUp = (event: KeyboardEvent) => keys.delete(event.code);
  const mouseDown = (event: MouseEvent) => {
    if (isControlling()) {
      buttons.add(event.button);
      position = event;
    }
  };
  const mouseUp = (event: MouseEvent) => buttons.delete(event.button);
  const mouseMove = (event: MouseEvent) => {
    position = event;
  };
  // Run after noVNC's target handlers, but before app-wide bubble-phase shortcuts.
  const stopKeyboard = (event: KeyboardEvent) => event.stopPropagation();
  canvas.addEventListener("keydown", keyDown, true);
  canvas.addEventListener("keyup", keyUp, true);
  canvas.addEventListener("mousedown", mouseDown, true);
  canvas.addEventListener("mouseup", mouseUp, true);
  canvas.addEventListener("mousemove", mouseMove, true);
  canvas.addEventListener("keydown", stopKeyboard);
  canvas.addEventListener("keyup", stopKeyboard);

  return {
    release() {
      for (const event of keys.values()) {
        canvas.dispatchEvent(
          new KeyboardEvent("keyup", {
            code: event.code,
            key: event.key,
            location: event.location,
            bubbles: false,
          })
        );
      }
      for (const button of buttons) {
        canvas.dispatchEvent(
          new MouseEvent("mouseup", {
            button,
            clientX: position.clientX,
            clientY: position.clientY,
            bubbles: false,
          })
        );
      }
      keys.clear();
      buttons.clear();
    },
    dispose() {
      keys.clear();
      buttons.clear();
      canvas.removeEventListener("keydown", keyDown, true);
      canvas.removeEventListener("keyup", keyUp, true);
      canvas.removeEventListener("mousedown", mouseDown, true);
      canvas.removeEventListener("mouseup", mouseUp, true);
      canvas.removeEventListener("mousemove", mouseMove, true);
      canvas.removeEventListener("keydown", stopKeyboard);
      canvas.removeEventListener("keyup", stopKeyboard);
    },
  };
}
