#!/usr/bin/env bash
# Generate version.ts with git information
#
# In CI release builds (RELEASE_TAG set), use the tag directly to avoid false
# "-dirty" stamps from CI artifacts (node_modules, build outputs, etc.).
# Local builds continue using git describe --dirty for accurate dev info.

set -euo pipefail

VERSION_FILE="src/version.ts"
TMP_FILE=$(mktemp)
trap 'rm -f "$TMP_FILE"' EXIT

# XUM_GIT_COMMIT overrides the commit stamp (e.g. Nix builds where .git is
# unavailable in the sandbox but the revision is known to the flake). Keep the
# old MUX_GIT_COMMIT alias for release jobs that have not migrated yet.
# Namespaced deliberately: plain GIT_COMMIT is exported ambiently by some CI
# systems (Jenkins) and could pair a stale commit with HEAD's describe.
GIT_COMMIT="${XUM_GIT_COMMIT:-${MUX_GIT_COMMIT:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}}"
# Reproducible builds: prefer SOURCE_DATE_EPOCH (Nix, reproducible-builds.org),
# then the HEAD commit time, then the wall clock (tarball builds without git).
BUILD_EPOCH="${SOURCE_DATE_EPOCH:-$(git log -1 --format=%ct 2>/dev/null || date -u +%s)}"
# BSD/macOS form first: -j never sets the clock, and GNU date rejects -j and falls through.
TIMESTAMP=$(date -u -j -f %s "$BUILD_EPOCH" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null \
  || date -u -d "@$BUILD_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")

if [ -n "${RELEASE_TAG:-}" ]; then
  # CI release: use the authoritative tag, never dirty
  GIT_DESCRIBE="$RELEASE_TAG"
  echo "Release build: using RELEASE_TAG=${RELEASE_TAG}"
else
  # Local/dev build: use git describe with dirty detection
  GIT_DESCRIBE=$(git describe --tags --always --dirty 2>/dev/null || echo "unknown")

  # Debug output for dirty builds
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --verify HEAD >/dev/null 2>&1; then
    if ! git diff-index --quiet HEAD -- 2>/dev/null; then
      echo "⚠️  Git checkout is dirty; version will be stamped with '-dirty'."
      echo "Tracked dirty files:"
      git diff-index --name-only HEAD -- | sed 's/^/  - /'
    fi
  fi
fi

cat >"$TMP_FILE" <<EOF
// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "${GIT_COMMIT}",
  git_describe: "${GIT_DESCRIBE}",
  buildTime: "${TIMESTAMP}",
};
EOF

if [ -f "$VERSION_FILE" ] && cmp -s "$TMP_FILE" "$VERSION_FILE"; then
  echo "version.ts already up to date: ${GIT_DESCRIBE} (${GIT_COMMIT}) at ${TIMESTAMP}"
  exit 0
fi

mv "$TMP_FILE" "$VERSION_FILE"
trap - EXIT

echo "Generated version.ts: ${GIT_DESCRIBE} (${GIT_COMMIT}) at ${TIMESTAMP}"
