/**
 * Unified executor for background bash processes.
 *
 * ALL bash commands are spawned through this executor with background-style
 * infrastructure (nohup, file output, exit code trap). This enables:
 *
 * 1. Uniform code path - one spawn mechanism for all bash commands
 * 2. Crash resilience - output always persisted to files
 * 3. Seamless fg→bg transition - "background this" = "stop waiting"
 *
 * Uses runtime.tempDir() for runtime-agnostic temp directory resolution.
 * Works identically for local and SSH runtimes.
 */

import type {
  Runtime,
  BackgroundHandle,
  BackgroundMonitorProbeResult,
  ExecStream,
} from "@/node/runtime/Runtime";
import * as fs from "fs/promises";
import * as path from "path";
import { log } from "./log";
import {
  buildWrapperScript,
  buildSpawnCommand,
  parsePid,
  parseExitCode,
  buildTerminateCommand,
  shellQuote,
} from "@/node/runtime/backgroundCommands";
import { execBuffered, writeFileString } from "@/node/utils/runtime/helpers";
import { LocalBaseRuntime } from "@/node/runtime/LocalBaseRuntime";
import { DevcontainerRuntime } from "@/node/runtime/DevcontainerRuntime";
import { NON_INTERACTIVE_ENV_VARS } from "@/common/constants/env";
import { toPosixPath } from "@/node/utils/paths";
import { getErrorMessage } from "@/common/utils/errors";

/**
 * Quote a path for shell commands.
 * On Windows, first converts to POSIX format, then shell-quotes.
 * On Unix, just shell-quotes (handles spaces, special chars).
 */
export function quotePathForShell(p: string): string {
  const posixPath = toPosixPath(p);
  return shellQuote(posixPath);
}

/**
 * Whether this runtime's background spawn records live on the HOST filesystem at
 * localBgWorkspaceDir with host-namespace PIDs. Only such records can be probed via local fs
 * reads and process.kill (crash-orphan archive gating, restart-unique name allocation).
 * DevcontainerRuntime extends LocalBaseRuntime but execs inside the container: its records
 * live under the container-side tempDir() (host-visible only through the workspace bind
 * mount) and its recorded PIDs are container-namespace, so it must be treated like a remote
 * runtime everywhere a probe would otherwise trust host paths or host PID checks.
 */
export function spawnRecordsAreHostLocal(runtime: Runtime): boolean {
  return runtime instanceof LocalBaseRuntime && !(runtime instanceof DevcontainerRuntime);
}

/**
 * Safe fallback cwd for runtime.exec() calls that don't need a specific workspace cwd.
 *
 * NOTE: Local runtimes validate that cwd exists before spawning, so this must be a real directory.
 */
const FALLBACK_CWD = process.platform === "win32" ? (process.env.TEMP ?? "C:\\") : "/tmp";

/** Helper to extract error message for logging */
function errorMsg(error: unknown): string {
  return getErrorMessage(error);
}

/** Subdirectory under temp for background process output */
export const BG_OUTPUT_SUBDIR = "mux-bashes";

/** Output filename for combined stdout/stderr */
const OUTPUT_FILENAME = "output.log";

/** Exit code filename */
const EXIT_CODE_FILENAME = "exit_code";

/** Per-process spawn-record filenames that survive an app crash (see localBgWorkspaceDir). */
export const BG_META_FILENAME = "meta.json";
export const BG_EXIT_CODE_FILENAME = EXIT_CODE_FILENAME;

/**
 * Local-filesystem directory holding this workspace's background spawn records (one
 * subdirectory per process with meta.json, output.log, and the wrapper's exit_code trap
 * file). Mirrors LocalBaseRuntime.tempDir(), which spawnProcess resolves when the process
 * was spawned on a local runtime. Crash-orphan detection scans this layout because the
 * records outlive the app while nohup/setsid children keep running.
 */
export function localBgWorkspaceDir(workspaceId: string): string {
  const tempRoot = process.platform === "win32" ? (process.env.TEMP ?? "C:\\Temp") : "/tmp";
  return `${tempRoot}/${BG_OUTPUT_SUBDIR}/${workspaceId}`;
}

/**
 * Compute paths for a background process output directory.
 * @param bgOutputDir Base directory (e.g., /tmp/mux-bashes or ~/.xum/sessions)
 * @param workspaceId Workspace identifier
 * @param processId Process identifier
 */
function computeOutputPaths(
  bgOutputDir: string,
  workspaceId: string,
  processId: string
): { outputDir: string; outputPath: string; exitCodePath: string } {
  const outputDir = `${bgOutputDir}/${workspaceId}/${processId}`;
  return {
    outputDir,
    outputPath: `${outputDir}/${OUTPUT_FILENAME}`,
    exitCodePath: `${outputDir}/${EXIT_CODE_FILENAME}`,
  };
}

/**
 * Options for spawning a process
 */
export interface SpawnOptions {
  /** Working directory for command execution */
  cwd: string;
  /** Workspace ID for output directory organization */
  workspaceId: string;
  /** Process ID (e.g., "bash_1") - generated by BackgroundProcessManager */
  processId: string;
  /** Environment variables to inject */
  env?: Record<string, string>;
}

/**
 * Result of spawning a process
 */
export type SpawnResult =
  | { success: true; handle: BackgroundHandle; pid: number; outputDir: string }
  | { success: false; error: string };

/**
 * Spawn a background process using runtime.exec (works for both local and SSH).
 *
 * All processes get the same infrastructure:
 * - nohup/setsid for process isolation
 * - stdout/stderr merged into single output.log with 2>&1
 * - Exit code captured via bash trap
 *
 * Uses runtime.tempDir() for output directory, making the code runtime-agnostic.
 *
 * @param runtime Runtime to spawn on
 * @param script Script to execute
 * @param options Spawn options
 */
export async function spawnProcess(
  runtime: Runtime,
  script: string,
  options: SpawnOptions
): Promise<SpawnResult> {
  log.debug(`BackgroundProcessExecutor.spawnProcess: Spawning in ${options.cwd}`);

  // Get temp directory from runtime (absolute path, runtime-agnostic)
  const tempDir = await runtime.tempDir();
  const bgOutputDir = `${tempDir}/${BG_OUTPUT_SUBDIR}`;
  const execCwd = runtime.mapPathForExec?.(options.cwd) ?? options.cwd;

  // Use shell-safe quoting for paths (handles spaces, special chars)
  const quotePath = quotePathForShell;

  // Verify working directory exists
  const cwdCheck = await execBuffered(runtime, `cd ${quotePath(execCwd)}`, {
    cwd: FALLBACK_CWD,
    timeout: 10,
  });
  if (cwdCheck.exitCode !== 0) {
    return { success: false, error: `Working directory does not exist: ${execCwd}` };
  }

  // Compute output paths (unified output.log instead of separate stdout/stderr)
  const { outputDir, outputPath, exitCodePath } = computeOutputPaths(
    bgOutputDir,
    options.workspaceId,
    options.processId
  );

  // A failed spawn must not leave a recordless process directory behind: the crash-orphan
  // probe fails closed on directories without readable metadata or an exit marker.
  const removeOutputDirBestEffort = async () => {
    try {
      await execBuffered(runtime, `rm -rf ${quotePath(outputDir)}`, {
        cwd: FALLBACK_CWD,
        timeout: 10,
      });
    } catch {
      // Best-effort: a leftover directory only over-refuses model-driven archives.
    }
  };

  // Create output directory and empty file
  try {
    await runtime.ensureDir(outputDir);
    await writeFileString(runtime, outputPath, "");
    // Process IDs are display-name based and only deduplicated within one app session, so a
    // restart can reuse a previous session's directory. A stale exit_code from that prior
    // process would be trusted as proof that the NEW process exited — both by getExitCode()
    // and by crash-orphan archive gating — so it must be gone before the wrapper's trap owns
    // the file again.
    const rmResult = await execBuffered(runtime, `rm -f ${quotePath(exitCodePath)}`, {
      cwd: FALLBACK_CWD,
      timeout: 10,
    });
    if (rmResult.exitCode !== 0) {
      await removeOutputDirBestEffort();
      return {
        success: false,
        error: `Failed to clear stale exit_code file: ${rmResult.stderr}`,
      };
    }
  } catch (error) {
    await removeOutputDirBestEffort();
    return {
      success: false,
      error: `Failed to create output directory: ${errorMsg(error)}`,
    };
  }

  // Build wrapper script (same for all runtimes now that paths are absolute)
  // Note: buildWrapperScript handles quoting internally via shellQuote
  const wrapperScript = buildWrapperScript({
    exitCodePath,
    cwd: execCwd,
    env: { ...options.env, ...NON_INTERACTIVE_ENV_VARS },
    script,
  });

  const spawnCommand = buildSpawnCommand({
    wrapperScript,
    outputPath,
    quotePath,
  });

  try {
    // No timeout - the spawn command backgrounds the process and returns immediately
    const result = await execBuffered(runtime, spawnCommand, {
      cwd: FALLBACK_CWD,
    });

    if (result.exitCode !== 0) {
      log.debug(`BackgroundProcessExecutor.spawnProcess: spawn command failed: ${result.stderr}`);
      await removeOutputDirBestEffort();
      return {
        success: false,
        error: `Failed to spawn background process: ${result.stderr}`,
      };
    }

    const pid = parsePid(result.stdout);
    if (!pid) {
      // Ambiguous launch: the spawn command succeeded (exit 0), so the detached shell is
      // likely running — only its PID echo was garbled (e.g. an SSH login banner prefixing
      // the output). Unlike the clean failures above, do NOT remove the directory: the
      // wrapper owns output.log/exit_code there, and on local runtimes a meta-less record
      // without an exit marker keeps hasOrphanedRunningBackgroundProcesses fail closed
      // until the trap writes the exit marker (self-healing). Deleting it would leave the
      // command running with no durable trace for archive gating to see. (Remote records
      // cannot feed the local probe; remote crash-orphan gating is tracked in #3944.)
      log.debug(`BackgroundProcessExecutor.spawnProcess: Invalid PID: ${result.stdout}`);
      return {
        success: false,
        error: `Failed to get valid PID from spawn: ${result.stdout}`,
      };
    }

    log.debug(`BackgroundProcessExecutor.spawnProcess: Spawned with PID ${pid}`);
    const handle = new RuntimeBackgroundHandle(runtime, pid, outputDir, quotePath);
    return { success: true, handle, pid, outputDir };
  } catch (error) {
    const errorMessage = errorMsg(error);
    log.debug(`BackgroundProcessExecutor.spawnProcess: Error: ${errorMessage}`);
    // Post-dispatch ambiguity: a transport-level throw (an SSH/Coder channel or container
    // exec error after the spawn command was sent) cannot prove the detached shell never
    // started — a remote/container exec can reject after dispatch while the nohup job
    // survives. Keep the directory as durable evidence: the wrapper's trap settles it with
    // an exit marker if the job did run, and non-host crash-orphan gating (#3944, plus the
    // devcontainer bind-mount scan) consumes exactly these records. Host-local exec throws
    // happen before anything is dispatched (spawn syscall failures), so those directories
    // are still removed — keeping one would permanently over-refuse archives with a record
    // no process will ever settle.
    if (spawnRecordsAreHostLocal(runtime)) {
      await removeOutputDirBestEffort();
    }
    return {
      success: false,
      error: `Failed to spawn background process: ${errorMessage}`,
    };
  }
}

/**
 * Unified handle to a background process.
 * Uses runtime.exec for all operations, working identically for local and SSH.
 *
 * Output files (output.log, exit_code) are on the runtime's filesystem.
 * This handle provides lifecycle management via execBuffered commands.
 */
class RuntimeBackgroundHandle implements BackgroundHandle {
  private terminated = false;

  constructor(
    private readonly runtime: Runtime,
    private readonly pid: number,
    public readonly outputDir: string,
    private readonly quotePath: (p: string) => string
  ) {}

  private assertMonitorProbeSucceeded(operation: string, exitCode: number): void {
    if (exitCode !== 0) {
      throw new Error(`${operation} exited with code ${exitCode}`);
    }
  }

  private async probeForMonitor<T>(
    probe: () => Promise<T>
  ): Promise<BackgroundMonitorProbeResult<T>> {
    try {
      return { success: true, value: await probe() };
    } catch (error) {
      return { success: false, error: errorMsg(error) };
    }
  }

  private async getExitCodeStrict(): Promise<number | null> {
    const exitCodePath = this.quotePath(`${this.outputDir}/${EXIT_CODE_FILENAME}`);
    // Absent marker means still running (exit 0, empty). File operators other than -h/-L
    // follow symlinks, so a dangling-symlink marker reads as absent to -e; require -L to
    // also fail before declaring absence, letting cat surface the dangling link (like any
    // other unreadable/replaced marker) as a probe failure instead of "running" forever.
    const result = await execBuffered(
      this.runtime,
      `{ [ ! -e ${exitCodePath} ] && [ ! -L ${exitCodePath} ]; } || cat ${exitCodePath} 2>/dev/null`,
      {
        cwd: FALLBACK_CWD,
        timeout: 10,
      }
    );
    this.assertMonitorProbeSucceeded("getExitCode", result.exitCode);
    const parsed = parseExitCode(result.stdout);
    // A nonempty marker that fails to parse is a corrupted write, not a still-running process.
    if (parsed == null && result.stdout.trim().length > 0) {
      throw new Error(`getExitCode marker is not a number: ${result.stdout.trim().slice(0, 32)}`);
    }
    return parsed;
  }

  /**
   * Get the exit code from the exit_code file.
   * Returns null if process is still running (file doesn't exist yet).
   */
  async getExitCode(): Promise<number | null> {
    try {
      return await this.getExitCodeStrict();
    } catch (error) {
      log.debug(`RuntimeBackgroundHandle.getExitCode: Error: ${errorMsg(error)}`);
      return null;
    }
  }

  getExitCodeForMonitor(): Promise<BackgroundMonitorProbeResult<number | null>> {
    return this.probeForMonitor(() => this.getExitCodeStrict());
  }

  /**
   * Terminate the process group.
   * Sends SIGTERM to process group, waits briefly, then SIGKILL if still running.
   */
  async terminate(): Promise<void> {
    if (this.terminated) return;

    try {
      const exitCodePath = `${this.outputDir}/${EXIT_CODE_FILENAME}`;
      const terminateCmd = buildTerminateCommand(this.pid, exitCodePath, this.quotePath);
      await execBuffered(this.runtime, terminateCmd, {
        cwd: FALLBACK_CWD,
        timeout: 15,
      });
      log.debug(`RuntimeBackgroundHandle: Terminated process group ${this.pid}`);
    } catch (error) {
      // Process may already be dead - that's fine
      log.debug(`RuntimeBackgroundHandle.terminate: Error: ${errorMsg(error)}`);
    }

    this.terminated = true;
  }

  /**
   * Clean up resources.
   * No resources to clean - process runs independently via nohup.
   */
  async dispose(): Promise<void> {
    // No resources to clean up
  }

  /**
   * Write meta.json to the output directory.
   */
  async writeMeta(metaJson: string): Promise<void> {
    // Persistence failures propagate: the initial spawn record is load-bearing for
    // crash-orphan archive gating (BackgroundProcessManager.spawn aborts the spawn when it
    // cannot be written); status-update callers wrap this in their own best-effort catch.
    const metaPath = this.quotePath(`${this.outputDir}/${BG_META_FILENAME}`);
    const result = await execBuffered(
      this.runtime,
      `cat > ${metaPath} << 'METAEOF'\n${metaJson}\nMETAEOF`,
      {
        cwd: FALLBACK_CWD,
        timeout: 10,
      }
    );
    if (result.exitCode !== 0) {
      throw new Error(`writeMeta failed with exit code ${result.exitCode}: ${result.stderr}`);
    }
  }

  private async readOutputFileSize(): Promise<number> {
    const filePath = this.quotePath(`${this.outputDir}/${OUTPUT_FILENAME}`);
    // No || fallback: a deleted or unreadable output file must fail the strict probe so the
    // monitor's failure policy can retire it instead of parsing the miss as an empty file.
    const sizeResult = await execBuffered(this.runtime, `wc -c < ${filePath} 2>/dev/null`, {
      cwd: FALLBACK_CWD,
      timeout: 10,
    });
    this.assertMonitorProbeSucceeded("readOutput file-size probe", sizeResult.exitCode);
    return parseInt(sizeResult.stdout.trim(), 10) || 0;
  }

  async getOutputFileSize(): Promise<number> {
    try {
      return await this.readOutputFileSize();
    } catch (error) {
      log.debug(`RuntimeBackgroundHandle.getOutputFileSize: Error: ${errorMsg(error)}`);
      return 0;
    }
  }

  private async readOutputStrict(offset: number): Promise<{ content: string; newOffset: number }> {
    const filePath = this.quotePath(`${this.outputDir}/${OUTPUT_FILENAME}`);
    const fileSize = await this.readOutputFileSize();

    if (offset >= fileSize) {
      return { content: "", newOffset: offset };
    }

    // Read from offset to end of file using tail -c (faster than dd bs=1)
    // tail -c +N means "start at byte N" (1-indexed)
    const readResult = await execBuffered(
      this.runtime,
      `tail -c +${offset + 1} ${filePath} 2>/dev/null`,
      { cwd: FALLBACK_CWD, timeout: 30 }
    );
    this.assertMonitorProbeSucceeded("readOutput tail probe", readResult.exitCode);

    return {
      content: readResult.stdout,
      newOffset: offset + Buffer.byteLength(readResult.stdout),
    };
  }

  /**
   * Read output from output.log at the given byte offset.
   * Uses tail -c to read from offset - works on both Linux and macOS.
   */
  async readOutput(offset: number): Promise<{ content: string; newOffset: number }> {
    try {
      return await this.readOutputStrict(offset);
    } catch (error) {
      log.debug(`RuntimeBackgroundHandle.readOutput: Error: ${errorMsg(error)}`);
      return { content: "", newOffset: offset };
    }
  }

  readOutputForMonitor(
    offset: number
  ): Promise<BackgroundMonitorProbeResult<{ content: string; newOffset: number }>> {
    return this.probeForMonitor(() => this.readOutputStrict(offset));
  }
}

/**
 * Options for migrating a foreground process to background
 */
export interface MigrateOptions {
  /** Working directory (for display in meta.json) */
  cwd: string;
  /** Workspace ID */
  workspaceId: string;
  /** Process ID (e.g., "bash_1") - generated by BackgroundProcessManager */
  processId: string;
  /** Original script being executed */
  script: string;
  /** Output already captured while running in foreground */
  existingOutput: string[];
  /** Human-readable name for the process */
  displayName?: string;
}

/**
 * Result of migrating a foreground process
 */
export type MigrateResult =
  | { success: true; handle: BackgroundHandle; outputDir: string }
  | { success: false; error: string };

/**
 * Migrate a foreground process to background tracking.
 *
 * This is called when user clicks "Background" on a running foreground process.
 * The process continues running, but we:
 * 1. Create output directory and write existing output
 * 2. Continue consuming streams and writing to unified output.log
 * 3. Track exit code when process completes
 * 4. Return a BackgroundHandle for the manager to track
 *
 * Note: Output files are written locally (not via runtime), so this works
 * for SSH runtime where streams are already being piped to the local machine.
 *
 * @param execStream The running process's streams
 * @param options Migration options
 * @param bgOutputDir Base directory for output files
 */
export async function migrateToBackground(
  execStream: ExecStream,
  options: MigrateOptions,
  bgOutputDir: string
): Promise<MigrateResult> {
  // Use shared path computation (path.join for local filesystem)
  const { outputDir, outputPath } = computeOutputPaths(
    bgOutputDir,
    options.workspaceId,
    options.processId
  );

  try {
    // Create output directory
    await fs.mkdir(outputDir, { recursive: true });

    // Write existing output to unified output.log
    await fs.writeFile(outputPath, options.existingOutput.join("\n") + "\n");

    // Create handle that will continue writing to file
    const handle = new MigratedBackgroundHandle(execStream, outputDir, outputPath);

    // Start consuming remaining output in background
    handle.startConsuming();

    return { success: true, handle, outputDir };
  } catch (error) {
    const errorMessage = errorMsg(error);
    log.debug(`migrateToBackground: Error: ${errorMessage}`);
    return { success: false, error: `Failed to migrate process: ${errorMessage}` };
  }
}

/**
 * Handle for a migrated foreground process.
 *
 * Unlike RuntimeBackgroundHandle which uses runtime.exec for file operations,
 * this handle uses local filesystem directly because the streams are already
 * being piped to the local machine (even for SSH runtime).
 *
 * Both stdout and stderr are written to a unified output.log file.
 */
class MigratedBackgroundHandle implements BackgroundHandle {
  private exitCodeValue: number | null = null;
  private consuming = false;
  private outputFd: fs.FileHandle | null = null;

  constructor(
    private readonly execStream: ExecStream,
    public readonly outputDir: string,
    private readonly outputPath: string
  ) {}

  /**
   * Start consuming remaining output from streams and writing to unified file.
   * Called after handle is created to begin background file writing.
   */
  startConsuming(): void {
    if (this.consuming) return;
    this.consuming = true;

    // Open output file once, consume both streams to it
    void this.consumeStreams();

    // Track exit code
    void this.execStream.exitCode.then((code) => {
      this.exitCodeValue = code;
      // Write exit code to file
      void this.writeExitCode(code);
    });
  }

  /**
   * Consume both stdout and stderr streams and append to unified output file.
   */
  private async consumeStreams(): Promise<void> {
    try {
      this.outputFd = await fs.open(this.outputPath, "a");

      // Consume both streams concurrently, both writing to same file
      await Promise.all([
        this.consumeStream(this.execStream.stdout),
        this.consumeStream(this.execStream.stderr),
      ]);
    } catch (error) {
      log.debug(`MigratedBackgroundHandle.consumeStreams: ${errorMsg(error)}`);
    } finally {
      if (this.outputFd) {
        await this.outputFd.close();
        this.outputFd = null;
      }
    }
  }

  /**
   * Consume a stream and append to the shared output file.
   */
  private async consumeStream(stream: ReadableStream<Uint8Array>): Promise<void> {
    try {
      const reader = stream.getReader();

      try {
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          if (value && this.outputFd) {
            await this.outputFd.write(value);
          }
        }
      } finally {
        reader.releaseLock();
      }
    } catch (error) {
      // Stream may have been cancelled or process killed - that's fine
      log.debug(`MigratedBackgroundHandle.consumeStream: ${errorMsg(error)}`);
    }
  }

  /**
   * Write exit code to file.
   */
  private async writeExitCode(code: number): Promise<void> {
    try {
      const exitCodePath = path.join(this.outputDir, EXIT_CODE_FILENAME);
      await fs.writeFile(exitCodePath, String(code));
    } catch (error) {
      log.debug(`MigratedBackgroundHandle.writeExitCode: ${errorMsg(error)}`);
    }
  }

  getExitCode(): Promise<number | null> {
    return Promise.resolve(this.exitCodeValue);
  }

  async terminate(): Promise<void> {
    // ExecStream doesn't expose a kill method directly
    // Cancel the streams to stop reading (process continues but we stop tracking)
    try {
      await this.execStream.stdout.cancel();
      await this.execStream.stderr.cancel();
    } catch {
      // Streams may already be closed
    }
  }

  async dispose(): Promise<void> {
    // Close any open file handles
    await this.outputFd?.close().catch(() => {
      /* ignore */
    });
  }

  async getOutputFileSize(): Promise<number> {
    try {
      const stat = await fs.stat(this.outputPath);
      return stat.size;
    } catch (error) {
      log.debug(`MigratedBackgroundHandle.getOutputFileSize: ${errorMsg(error)}`);
      return 0;
    }
  }

  async writeMeta(metaJson: string): Promise<void> {
    // Swallowed on purpose (unlike RuntimeBackgroundHandle): registerMigratedProcess writes
    // fire-and-forget (a rethrow would surface as an unhandled rejection), and a missing
    // migrated record errs toward over-refusal, never under-refusal — the crash-orphan probe
    // fails closed on markerless pid-0 records and on unreadable ones alike.
    try {
      const metaPath = path.join(this.outputDir, BG_META_FILENAME);
      await fs.writeFile(metaPath, metaJson);
    } catch (error) {
      log.debug(`MigratedBackgroundHandle.writeMeta: ${errorMsg(error)}`);
    }
  }

  async readOutput(offset: number): Promise<{ content: string; newOffset: number }> {
    try {
      const fileSize = await this.getOutputFileSize();

      if (offset >= fileSize) {
        return { content: "", newOffset: offset };
      }

      // Read from offset to end
      const fd = await fs.open(this.outputPath, "r");
      try {
        const buffer = Buffer.alloc(fileSize - offset);
        const { bytesRead } = await fd.read(buffer, 0, buffer.length, offset);
        return {
          content: buffer.slice(0, bytesRead).toString("utf-8"),
          newOffset: offset + bytesRead,
        };
      } finally {
        await fd.close();
      }
    } catch (error) {
      log.debug(`MigratedBackgroundHandle.readOutput: ${errorMsg(error)}`);
      return { content: "", newOffset: offset };
    }
  }
}
